version: 2

sources:
  - name: staging
    database: DE_PROJECT
    schema: STAGING

    tables:
      - name: STG_TRIPS
      - name: STG_DRIVERS
      - name: STG_TRUCKS
      - name: STG_LOADS
      - name: STG_TRAILERS
      - name: STG_SAFETY_INCIDENTS
      - name: STG_ROUTES
      
      
      



    