version: 2

sources:
  - name: staging
    database: DE_PROJECT
    schema: STAGING

    tables:
      - name: STG_TRIPS
      - name: STG_DRIVERS
      - name: STG_TRUCKS
      - name: STG_LOADS
      - name: STG_TRAILERS
      - name: STG_SAFETY_INCIDENTS
      - name: STG_ROUTES
      - name: STG_MAINTENANCE_RECORDS
      - name: STG_FUEL_PURCHASES
      - name: STG_FACILITIES
      - name: STG_DRIVER_MONTHLY_METRICS
      - name: STG_DELIVERY_EVENTS
      - name: STG_CUSTOMERS
      - name: STG_WEATHER




    