version: 2

models:
  - name: stg_drivers_clean
    description: "Cleaned driver data."

    columns:
      - name: driver_id
        description: "Unique identifier for each driver."
        tests:
          - unique
          - not_null

      - name: hire_date
        description: "Date the driver was hired."
        tests:
          - not_null

      - name: date_of_birth
        description: "Driver's date of birth."
        tests:
          - not_null

  - name: stg_trucks_clean
    description: "Cleaned truck data."

    columns:
      - name: trip_id
        description: "Unique identifier for each trip."
        tests:
          - unique
          - not_null          

      - name: dispatch_date
        description: "Date the trip was dispatched."
        tests:
          - not_null
  - name: stg_loads_clean
    description: "Cleaned loads data."

    columns:
      - name: load_id
        description: "Unique identifier for each load."
        tests:
          - unique
          - not_null

      - name: customer_id
        description: "Unique identifier for each customer."
        tests:
        - not_null

      - name: load_date
        description: "Date the load was created."
        tests:
          - not_null
  - name: stg_trips_clean
    description: "Cleaned trips data."
    columns:
      - name: trip_id
        description: "Unique identifier for each trip."
        tests:
          - unique
          - not_null

      - name: dispatch_date
        description: "Date the trip was dispatched."
        tests:
          - not_null
      
  - name: stg_trailers_clean
    description: "Cleaned trailers data."

    columns:
      - name: trailer_id
        description: "Unique identifier for each trailer."
        tests:
          - unique
          - not_null

      - name: vin
        description: "Vehicle Identification Number of the trailer."
        tests:
          - unique
          - not_null

      - name: trailer_number
        description: "Unique number assigned to the trailer."
        tests:
          - not_null

  - name: stg_safety_incidents_clean
    description: "Cleaned safety incidents data."

    columns:
      - name: incident_id
        description: "Unique identifier for each safety incident."
        tests:
          - unique
          - not_null

      - name: incident_date
        description: "Date the safety incident occurred."
        tests:
          - not_null

      - name: driver_id
        description: "Unique identifier for the driver involved in the incident."
        tests:
          - not_null  

      - name: incident_type
        description: "Type of safety incident."
        tests:
          - not_null

      - name: description
        description: "Detailed description of the safety incident."
        tests:
          - not_null


      - name: injury_flag
        description: "Flag indicating if the incident resulted in an injury."
        tests:
          - not_null

      - name: preventable_flag
        description: "Flag indicating if the incident was preventable."
        tests:
          - not_null                      

  - name: stg_routes_clean
    description: "Cleaned routes data."

    columns:
      - name: route_id
        description: "Unique identifier for each route."
        tests:
          - unique
          - not_null

      - name: origin_state
        description: "Starting location of the route."
        tests:
          - not_null

      - name: destination_city
        description: "Ending location of the route."
        tests:
          - not_null

      - name: destination_state
        description: "Ending location of the route."
        tests:
          - not_null

      - name: typical_transit_days
        description: "Typical number of days for transit on this route."
        tests:
          - not_null

      - name: typical_distance_miles
        description: "Typical distance in miles for this route."
        tests:
          - not_null    
                  


      